import "@/styles/globals.css";

import { MainHeader } from "@/components/layout/main-header";

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Sample",
  description: "Generated by create next app",
};

export default function RootLayout(props: RootLayoutProps) {
  return (
    <html lang="ja">
      <body className="">
        <MainHeader />
        {props.children}
      </body>
    </html>
  );
}
