name: Countinuous Integration

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: "23.5.0"
  PNPM_VERSION: "9.15.4"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup enviroment
        uses: ./.github/actions/setup
        with:
          node-version: ${{env.NODE_VERSION}}
          pnpm-version: ${{env.PNPM_VERSION}}

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{env.NODE_VERSION}}
          pnpm-version: ${{env.PNPM_VERSION}}
      - run: pnpm run lint

  format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{env.NODE_VERSION}}
          pnpm-version: ${{env.PNPM_VERSION}}
      - run: pnpm run format

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{env.NODE_VERSION}}
          pnpm-version: ${{env.PNPM_VERSION}}
      - run: pnpm run typecheck
